{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sk.ccregisterx",
    "module": "ccregisterx",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "nmr23fuhdrd3ngjc3oyrxc2io4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ccregisterx-0.0.1.jar",
          "url": "ccregisterx-0.0.1.jar",
          "size": 149599,
          "sha512": "4bf6c8a221f98991f3377b6626c593939bd8882978ac4f9522eac70a2a74d4d9c4028b5f341dbd3208455a961acf3fc7e5f26e9510ad5410340d47d2ce1ce8ca",
          "sha256": "ba1c9ea5745adf678e772ae38435e51d655051a899ecbc6c2e6ef8f346c77d1d",
          "sha1": "0f4b336d5d1a9d56ab79ff28ea696f579dfea442",
          "md5": "3c9e43f26160a4a9166deb787d93a092"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ccregisterx-0.0.1.jar",
          "url": "ccregisterx-0.0.1.jar",
          "size": 149599,
          "sha512": "4bf6c8a221f98991f3377b6626c593939bd8882978ac4f9522eac70a2a74d4d9c4028b5f341dbd3208455a961acf3fc7e5f26e9510ad5410340d47d2ce1ce8ca",
          "sha256": "ba1c9ea5745adf678e772ae38435e51d655051a899ecbc6c2e6ef8f346c77d1d",
          "sha1": "0f4b336d5d1a9d56ab79ff28ea696f579dfea442",
          "md5": "3c9e43f26160a4a9166deb787d93a092"
        }
      ]
    }
  ]
}
