{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sk.ccregisterx",
    "module": "ccregisterx",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "4ngbqbkxxnftlk5yd4rihod66q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ccregisterx-0.0.1.jar",
          "url": "ccregisterx-0.0.1.jar",
          "size": 149808,
          "sha512": "54942b5d6104cc7e3a0afcba91a1fe11b5b36e11a2a1fc33b2628f0f09df38219dd535933b374cfd8d8e7584a081746067d76d3bf905f24ae80e5252b0d4f918",
          "sha256": "a491f56f3df7d6c559281d19b69caf3dfa1c20b8f160f35bcfcfba0938010089",
          "sha1": "387ccbc78f485adb21088e6caa376a07c21ac3d6",
          "md5": "a967aea4abf3c571bd8082535e539688"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ccregisterx-0.0.1.jar",
          "url": "ccregisterx-0.0.1.jar",
          "size": 149808,
          "sha512": "54942b5d6104cc7e3a0afcba91a1fe11b5b36e11a2a1fc33b2628f0f09df38219dd535933b374cfd8d8e7584a081746067d76d3bf905f24ae80e5252b0d4f918",
          "sha256": "a491f56f3df7d6c559281d19b69caf3dfa1c20b8f160f35bcfcfba0938010089",
          "sha1": "387ccbc78f485adb21088e6caa376a07c21ac3d6",
          "md5": "a967aea4abf3c571bd8082535e539688"
        }
      ]
    }
  ]
}
